version: '3.9'
services:
  api:
    build:
      # UID and USER need to be exported e.g.:
      # export UID USER
      # This allows compose to run the app as the local development user.
      args:
        - UID
        - USER
      context: .
      target: development
    depends_on:
      - db
    env_file: .env
    ports:
      - 4000:3000
    restart: unless-stopped
    volumes:
      - ${PWD}:/app

  db:
    env_file: .env
    image: mariadb:10.5
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5-apache
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    ports:
      - 4001:80
