version: '3.8'
services:
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  db:
    image: mariadb:10.5
    container_name: db
    restart: always
    # ports:
    #   - '5432:5432'
    env_file:
      - .env
    #volumes:
    #  - mysql:/var/lib/mysql

# volumes:
#   mysql: