version: '3.8'
services:
  api:
    build:
      args:
        - NODE_ENV
        - UID
        - USER
      context: .
      target: development
    depends_on:
      - db
    env_file: .env
    ports:
      - 4000:4000
    restart: unless-stopped
    volumes:
      - ${PWD}:/app

  db:
    env_file: .env
    image: mariadb:10.5
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5-apache
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
    # PMA_PASSWORD
    # PMA_USER
    env_file: .env
    ports:
      - 4001:80
